version: "3.8"
services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - /tmp/data:/data # TODO: change the volume directory if is needed
    env_file:
      - .env
    command: server /data --console-address ":9090"

  create-bucket:
    image: minio/mc
    container_name: minio-create-bucket
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      echo 'Configuring MinIO client...';
      /usr/bin/mc alias set myminio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
      echo 'Creating documents bucket...';
      /usr/bin/mc mb myminio/documents --ignore-existing;
      echo 'Bucket created successfully!';
      exit 0;
      "
