export const CHUNKING_LIMITS = {
  MAX_CHUNKS_PER_DOCUMENT: 500,
  MAX_CHUNK_SIZE: 2000,
  MIN_CHUNK_SIZE: 50,
  DEFAULT_CHUNK_SIZE: 1000,
  MAX_OVERLAP: 200,
  DEFAULT_OVERLAP: 100,
  MAX_DOCUMENT_SIZE_BYTES: 10 * 1024 * 1024,
  MAX_TEXT_LENGTH_CHARS: 1000000,
} as const;

export const CHUNKING_DEFAULTS = {
  maxChunkSize: CHUNKING_LIMITS.DEFAULT_CHUNK_SIZE,
  overlap: CHUNKING_LIMITS.DEFAULT_OVERLAP,
  respectParagraphs: true,
  respectSentences: true,
  minChunkSize: CHUNKING_LIMITS.MIN_CHUNK_SIZE,
} as const;
