name: CI (client)

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'client/**'
      - 'backend/**'  # ← AÑADIR backend
      - '.github/workflows/ci-client.yml'
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - 'backend/**'  # ← AÑADIR backend
      - '.github/workflows/ci-client.yml'

permissions:
  contents: read

jobs:
  test:
    name: Lint, Test, Build (${{ matrix.node }})
    runs-on: ubuntu-latest

    services:
      postgres:
        image: pgvector/pgvector:pg15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=20

    env:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/testdb
      JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      OPENAI_API_KEY: "fake_key"
      AI_API_KEY: "fake_key"

    timeout-minutes: 30
    strategy:
      matrix:
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: |
            client/package-lock.json
            backend/package-lock.json  # ← AÑADIR cache para backend

      # PRIMERO instalar backend (para Prisma)
      - name: Install backend deps
        working-directory: backend
        run: npm ci

      # Configurar DB ANTES de frontend
      - name: Wait for Postgres
        run: |
          echo "Waiting for Postgres..."
          for i in {1..30}; do
            if pg_isready -h postgres -U postgres; then
              echo "Postgres is ready!"
              exit 0
            fi
            echo "Waiting... attempt $i"
            sleep 2
          done
          echo "Postgres never became ready"
          exit 1

      - name: Setup DB (Prisma migrate + reset)
        working-directory: backend
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          npx prisma generate
          npx prisma migrate reset --force

      - name: Seed DB
        working-directory: backend
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: npm run seed

      # AHORA instalar y testear frontend
      - name: Install frontend deps
        working-directory: client
        run: npm ci

      - name: Lint
        working-directory: client
        run: npm run lint --if-present

      - name: Test (Jest)
        working-directory: client
        run: npm run test --if-present -- --ci --reporters=default --reporters=jest-junit --outputFile=junit.xml || echo "tests finished"

      - name: Build
        working-directory: client
        run: npm run build --if-present

      - name: Setup Docker (solo minio)
        working-directory: infra/docker
        run: |
          docker compose -f minio.compose.yml up -d

      - name: E2E (Cypress)
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          start: npm run start:e2e
          wait-on: http://localhost:5173
          wait-on-timeout: 120
          command: npm run cypress:run -- --spec cypress/e2e/login.spec.ts

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-and-reports-${{ matrix.node }}
          path: |
            client/dist/**
            client/junit.xml
