name: CI (client)

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'client/**'
      - '.github/workflows/ci-client.yml'
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - '.github/workflows/ci-client.yml'

permissions:
  contents: read

jobs:
  test:
    name: Lint, Test, Build (${{ matrix.node }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install
        working-directory: client
        run: npm ci

      - name: Lint
        working-directory: client
        run: npm run lint --if-present

      - name: Test
        working-directory: client
        run: npm run test --if-present -- --ci --reporters=default --reporters=junit --outputFile=junit.xml

      - name: Build
        working-directory: client
        run: npm run build --if-present


